name: Build and Deploy
on:
  push:
    tags:
      - v*

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t recogio/stringer:sample .