name: Deploy
on:
  push:
    tags:
      - v*

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Log in to registry
        run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build Docker Image
        run: docker build -t recogio/stringer:${GITHUB_REF##*/} .

      - name: Deploy Docker Image
        run: docker push recogio/stringer:${GITHUB_REF##*/}